version: '3.9'
services:
  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  api:
    build:
      context: ./backend
    ports:
      - '4000:4000'
    env_file:
      - ./backend/.env.example
    depends_on:
      - mongo
      - redis
  web:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env.example
    depends_on:
      - api
volumes:
  mongo_data:
