import { Schema, model } from 'mongoose';

export const Notification = model('Notification', new Schema({ userId: { type: Schema.Types.ObjectId, ref: 'User', index: true }, title: String, body: String, type: String, readAt: Date }, { timestamps: true }));
export const Preference = model('Preference', new Schema({ userId: { type: Schema.Types.ObjectId, ref: 'User', unique: true, index: true }, emailUpdates: Boolean, whatsappUpdates: Boolean, dailyProgressReport: Boolean, escalationAlerts: Boolean, autoGenerateDocuments: Boolean, assistantUpdates: Boolean }, { timestamps: true }));
export const ApplicationAnswer = model('ApplicationAnswer', new Schema({ userId: { type: Schema.Types.ObjectId, ref: 'User', unique: true, index: true }, answers: Schema.Types.Mixed }, { timestamps: true }));
export const AuditLog = model('AuditLog', new Schema({ actorId: { type: Schema.Types.ObjectId, ref: 'User', index: true }, action: String, targetType: String, targetId: String, metadata: Schema.Types.Mixed }, { timestamps: true }));
export const ActivityLog = model('ActivityLog', new Schema({ userId: { type: Schema.Types.ObjectId, ref: 'User', index: true }, event: String, metadata: Schema.Types.Mixed }, { timestamps: true }));
